# Generated by Django 4.0.4 on 2022-06-04 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('author', models.CharField(max_length=150, verbose_name='Автор')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Картина')),
                ('description', models.TextField(verbose_name='Описание')),
                ('style', models.CharField(choices=[('REN', 'Ренессанс'), ('MAN', 'Маньеризм'), ('BAR', 'Барокко'), ('CLA', 'Классицизм'), ('ROM', 'Романтизм'), ('IMP', 'Импрессионизм'), ('EXP', 'Экспрессионизм'), ('AVA', 'Авангард'), ('OTH', 'Другой')], default='OTH', max_length=3, verbose_name='Стиль')),
                ('genre', models.CharField(choices=[('POR', 'Портрет'), ('PEI', 'Пейзаж'), ('MAR', 'Марина'), ('IST', 'Исторический'), ('BAT', 'Батальный'), ('ANI', 'Анималистика'), ('BIT', 'Бытовой'), ('NAT', 'Натюрморт'), ('ARH', 'Архитектурный'), ('NU', 'Жанр Ню'), ('OTH', 'Другой')], default='OTH', max_length=3, verbose_name='Жанр')),
                ('technique', models.CharField(choices=[('MAS', 'Масляная'), ('AKR', 'Акриловая'), ('AKV', 'Акварель'), ('TEM', 'Темпера'), ('GUA', 'Гуашь'), ('TUS', 'Тушь'), ('PAS', 'Пастель'), ('ANC', 'Энкаустика'), ('AER', 'Аэрография'), ('SME', 'Смешанная'), ('OTH', 'Другая')], default='OTH', max_length=3, verbose_name='Техника')),
                ('published_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Liked_art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station.art')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
